### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by tdotdm** [nicomontanari/react-native-material-chip#1]
Hi, 

Is it possible to change the text color? 

Thanks.

**Comment by nicomontanari** [comment]
Hi @tdotdm! The style of the text cannot currently be changed, but if it can be useful it can be implemented.

**Comment by roqkabel** [comment]
> Hi @tdotdm! The style of the text cannot currently be changed, but if it can be useful it can be implemented.

Sure thing, it will be nice to change the text color as well as the border color since you can able to change the background color

**Comment by nicomontanari** [comment]
@roqkabel you are right, in the next few days I will implement these changes and will release a new version.

**Comment by nicomontanari** [comment]
Hi @roqkabel, this feature was implemented in the pr #2. I already deployed a new npm version.
